const timelineElements = [
  { id: 1, title: "", description: "", date: "October 23, 2022", highlight: "/highlights/highlight1.mp4" },
  { id: 2, title: "", description: "", date: "November 25, 2022", highlight: "/highlights/highlight2.mp4" },
  { id: 3, title: "", description: "", date: "December 29, 2022", highlight: "/highlights/highlight3.mp4" },
  { id: 4, title: "", description: "", date: "January 1, 2023", highlight: "/highlights/highlight4.mp4" },
  { id: 5, title: "", description: "", date: "January 2, 2023", highlight: "/highlights/highlight5.mp4" },
  { id: 6, title: "", description: "", date: "January 2, 2023", highlight: "/highlights/highlight6.mp4" },
  { id: 7, title: "", description: "", date: "January 6, 2023", highlight: "/highlights/highlight7.mp4" },
  { id: 8, title: "", description: "", date: "January 21, 2023", highlight: "/highlights/highlight8.mp4" },
  { id: 9, title: "", description: "", date: "February 11, 2023", highlight: "/highlights/highlight9.mp4" },
  { id: 10, title: "", description: "", date: "February, 13, 2023", highlight: "/highlights/highlight10.mp4" },
  { id: 11, title: "", description: "", date: "February, 22, 2023", highlight: "/highlights/highlight11.mp4" },
  { id: 12, title: "", description: "", date: "February, 25, 2023", highlight: "/highlights/highlight12.mp4" },
  { id: 13, title: "", description: "", date: "March 19, 2023", highlight: "/highlights/highlight13.mp4" },
  { id: 14, title: "", description: "", date: "April 17, 2023", highlight: "/highlights/highlight14.mp4" },
  { id: 15, title: "", description: "", date: "April 18, 2023", highlight: "/highlights/highlight15.mp4" },
  { id: 16, title: "", description: "", date: "May 21, 2023", highlight: "/highlights/highlight16.mp4" },
  { id: 17, title: "", description: "", date: "June 7, 2023", highlight: "/highlights/highlight17.mp4" },
  { id: 18, title: "", description: "", date: "June 24, 2023", highlight: "/highlights/highlight18.mp4" },
  { id: 19, title: "", description: "", date: "July 5, 2023", highlight: "/highlights/highlight19.mp4" },
  { id: 20, title: "", description: "", date: "July 15, 2023", highlight: "/highlights/highlight20.mp4" },
  { id: 21, title: "", description: "", date: "July 15, 2023", highlight: "/highlights/highlight21.mp4" },
  { id: 22, title: "", description: "", date: "July 15, 2023", highlight: "/highlights/highlight22.mp4" },
  { id: 23, title: "", description: "", date: "July 30, 2023", highlight: "/highlights/highlight23.mp4" },
  { id: 24, title: "", description: "", date: "August 4, 2023", highlight: "/highlights/highlight24.mp4" },
  { id: 25, title: "", description: "", date: "September 3, 2023", highlight: "/highlights/highlight25.mp4" },
  { id: 26, title: "", description: "", date: "September 23, 2023", highlight: "/highlights/highlight26.mp4" },
  { id: 27, title: "", description: "", date: "Ocotber 17, 2023", highlight: "/highlights/highlight27.mp4" },
  { id: 28, title: "", description: "", date: "Ocotber 17, 2023", highlight: "/highlights/highlight28.mp4" },
  { id: 29, title: "", description: "", date: "October 23, 2023", highlight: "/highlights/highlight29.mp4" },
  { id: 30, title: "", description: "", date: "November 11, 2023", highlight: "/highlights/highlight30.mp4" },
  { id: 31, title: "", description: "", date: "November 18, 2023", highlight: "/highlights/highlight31.mp4" },
  { id: 32, title: "", description: "", date: "December 26, 2023", highlight: "/highlights/highlight32.mp4" },
  { id: 33, title: "", description: "", date: "December 27, 2023", highlight: "/highlights/highlight33.mp4" },
  { id: 34, title: "", description: "", date: "April 10, 2024", highlight: "/highlights/highlight34.mp4" },
  { id: 35, title: "", description: "", date: "June 7, 2024", highlight: "/highlights/highlight35.mp4" },
  { id: 36, title: "", description: "", date: "July 27, 2024", highlight: "/highlights/highlight36.mp4" },
  { id: 37, title: "", description: "", date: "August 17, 2024", highlight: "/highlights/highlight37.mp4" },
  { id: 38, title: "", description: "", date: "August 24, 2024", highlight: "/highlights/highlight38.mp4" },
  { id: 39, title: "", description: "", date: "September 14, 2024", highlight: "/highlights/highlight39.mp4" },
  { id: 40, title: "", description: "", date: "November 16, 2024", highlight: "/highlights/highlight40.mp4" },
  { id: 41, title: "", description: "", date: "December 17, 2024", highlight: "/highlights/highlight41.mp4" },
  { id: 42, title: "", description: "", date: "December 28, 2024", highlight: "/highlights/highlight42.mp4" }
];

export default timelineElements.reverse();
