const timelineElements = [
  { id: 1, title: "", description: "", date: "", highlight: "/highlights/highlight1.mp4" },
  { id: 2, title: "", description: "", date: "", highlight: "/highlights/highlight2.mp4" },
  { id: 3, title: "", description: "", date: "", highlight: "/highlights/highlight3.mp4" },
  { id: 4, title: "", description: "", date: "", highlight: "/highlights/highlight4.mp4" },
  { id: 5, title: "", description: "", date: "", highlight: "/highlights/highlight5.mp4" },
  { id: 6, title: "", description: "", date: "", highlight: "/highlights/highlight6.mp4" },
  { id: 7, title: "", description: "", date: "", highlight: "/highlights/highlight7.mp4" },
  { id: 8, title: "", description: "", date: "", highlight: "/highlights/highlight8.mp4" },
  { id: 9, title: "", description: "", date: "", highlight: "/highlights/highlight9.mp4" },
  { id: 10, title: "", description: "", date: "", highlight: "/highlights/highlight10.mp4" },
  { id: 11, title: "", description: "", date: "", highlight: "/highlights/highlight11.mp4" },
  { id: 12, title: "", description: "", date: "", highlight: "/highlights/highlight12.mp4" },
  { id: 13, title: "", description: "", date: "", highlight: "/highlights/highlight13.mp4" },
  { id: 14, title: "", description: "", date: "", highlight: "/highlights/highlight14.mp4" },
  { id: 15, title: "", description: "", date: "", highlight: "/highlights/highlight15.mp4" },
  { id: 16, title: "", description: "", date: "", highlight: "/highlights/highlight16.mp4" },
  { id: 17, title: "", description: "", date: "", highlight: "/highlights/highlight17.mp4" },
  { id: 18, title: "", description: "", date: "", highlight: "/highlights/highlight18.mp4" },
  { id: 19, title: "", description: "", date: "", highlight: "/highlights/highlight19.mp4" },
  { id: 20, title: "", description: "", date: "", highlight: "/highlights/highlight20.mp4" },
  { id: 21, title: "", description: "", date: "", highlight: "/highlights/highlight21.mp4" },
  { id: 22, title: "", description: "", date: "", highlight: "/highlights/highlight22.mp4" },
  { id: 23, title: "", description: "", date: "", highlight: "/highlights/highlight23.mp4" },
  { id: 24, title: "", description: "", date: "", highlight: "/highlights/highlight24.mp4" },
  { id: 25, title: "", description: "", date: "", highlight: "/highlights/highlight25.mp4" },
  { id: 26, title: "", description: "", date: "", highlight: "/highlights/highlight26.mp4" },
  { id: 27, title: "", description: "", date: "", highlight: "/highlights/highlight27.mp4" },
  { id: 28, title: "", description: "", date: "", highlight: "/highlights/highlight28.mp4" },
  { id: 29, title: "", description: "", date: "", highlight: "/highlights/highlight29.mp4" },
  { id: 30, title: "", description: "", date: "", highlight: "/highlights/highlight30.mp4" },
  { id: 31, title: "", description: "", date: "", highlight: "/highlights/highlight31.mp4" },
  { id: 32, title: "", description: "", date: "", highlight: "/highlights/highlight32.mp4" },
  { id: 33, title: "", description: "", date: "", highlight: "/highlights/highlight33.mp4" },
  { id: 34, title: "", description: "", date: "", highlight: "/highlights/highlight34.mp4" },
  { id: 35, title: "", description: "", date: "", highlight: "/highlights/highlight35.mp4" },
  { id: 36, title: "", description: "", date: "", highlight: "/highlights/highlight36.mp4" },
  { id: 37, title: "", description: "", date: "", highlight: "/highlights/highlight37.mp4" },
  { id: 38, title: "", description: "", date: "", highlight: "/highlights/highlight38.mp4" },
  { id: 39, title: "", description: "", date: "", highlight: "/highlights/highlight39.mp4" },
  { id: 40, title: "", description: "", date: "", highlight: "/highlights/highlight40.mp4" },
  { id: 41, title: "", description: "", date: "", highlight: "/highlights/highlight41.mp4" },
  { id: 42, title: "", description: "", date: "", highlight: "/highlights/highlight42.mp4" }
];

export default timelineElements.reverse();
